# 使用 Python 3.9 基础镜像
FROM python:3.9-slim

WORKDIR /app

# 复制依赖文件
COPY requirements.txt requirements.txt

# 安装依赖
RUN pip install -r requirements.txt

# 复制应用代码
COPY . /app

# 启动 Flask 应用
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]

