# 使用 Python 3.9 基础镜像
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt

# 设置环境变量
ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

#RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install -r requirements.txt 

COPY . .

CMD ["streamlit", "run", "app/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
